-- ============================================================
-- 약통 ERP - OCI Autonomous Database 스키마 (ADMIN 계정)
-- 실행 방법: OCI Database Actions > SQL 에서 전체 붙여넣고 실행
-- 전략: 1) 시퀀스  2) 테이블(FK 없이)  3) FK 일괄 추가  4) 인덱스
--       → 순서 문제 없이 한 번에 실행 가능
-- ============================================================

-- ============================================================
-- 1. 시퀀스
-- ============================================================
CREATE SEQUENCE SEQ_SETTLEMENT     START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_AR             START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_RECEIVING      START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_RECEIVING_DTL  START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_SPEC           START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_PO             START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_PO_DETAIL      START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_SHIPMENT       START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_SHIPMENT_DTL   START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_SUPPLIER       START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_API_LOG        START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_CUSTOMER       START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_INVENTORY_LOT  START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_AP             START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_EMPLOYEE       START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_RETURN         START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_SO             START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_SO_DETAIL      START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_PAYMENT        START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_DEPT           START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_ALERT          START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_MOVEMENT       START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_ATTENDANCE     START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_PURCHASE_INV   START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_SALES_INV      START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_AI_REPORT      START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_DISPOSAL       START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_AI_QUERY       START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_PRODUCT        START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_RETURN_REQUEST_GROUP_ID START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_DEPT_ROLE_EXCEPTION     START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- ============================================================
-- 2. 테이블 (FK 제약 없이 먼저 생성 - 순서 무관)
-- ============================================================

-- 부서
CREATE TABLE DEPARTMENT (
    DEPT_ID     NUMBER          NOT NULL,
    DEPT_NAME   VARCHAR2(50)    NOT NULL,
    DEPT_CODE   VARCHAR2(20)    NULL,
    DESCRIPTION VARCHAR2(300)   NULL,
    USE_YN      CHAR(1)         DEFAULT 'Y' NOT NULL,
    CREATED_AT  DATE            NULL,
    CONSTRAINT PK_DEPARTMENT PRIMARY KEY (DEPT_ID)
);

-- 직원
CREATE TABLE EMPLOYEE (
    EMP_ID      NUMBER          NOT NULL,
    LOGIN_ID    VARCHAR2(50)    NOT NULL,
    PASSWORD    VARCHAR2(255)   NOT NULL,
    EMP_NAME    VARCHAR2(50)    NOT NULL,
    PHONE       VARCHAR2(20)    NULL,
    EMAIL       VARCHAR2(100)   NULL,
    ROLE_CODE   NUMBER          NOT NULL,
    DEPT_ID     NUMBER          NULL,
    HIRE_DATE   DATE            NULL,
    STATUS      VARCHAR2(20)    DEFAULT 'ACTIVE' NOT NULL,
    CREATED_AT  DATE            NULL,
    UPDATED_AT  DATE            NULL,
    CONSTRAINT PK_EMPLOYEE PRIMARY KEY (EMP_ID)
);

-- 리프레시 토큰
CREATE TABLE REFRESH_TOKEN (
    JWT_ID      VARCHAR2(36)    NOT NULL,
    EMP_ID      INTEGER         NOT NULL,
    EXPIRES_AT  TIMESTAMP       NOT NULL
);

-- 부서 × 역할 예외 권한
CREATE TABLE DEPT_ROLE_EXCEPTION (
    EXCEPTION_ID    NUMBER          NOT NULL,
    DEPT_CODE       VARCHAR2(20)    NOT NULL,
    ROLE_CODE       VARCHAR2(20)    NOT NULL,
    EXCEPTION_TITLE VARCHAR2(100)   NOT NULL,
    EXCEPTION_AUTH  VARCHAR2(50)    NOT NULL,
    DESCRIPTION     VARCHAR2(500),
    USE_YN          CHAR(1)         DEFAULT 'Y' NOT NULL,
    CREATED_AT      DATE            DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_DEPT_ROLE_EXCEPTION PRIMARY KEY (EXCEPTION_ID),
    CONSTRAINT UQ_DRE_COMBO UNIQUE (DEPT_CODE, ROLE_CODE, EXCEPTION_AUTH),
    CONSTRAINT CK_DRE_USE_YN CHECK (USE_YN IN ('Y', 'N'))
);

-- 근태
CREATE TABLE ATTENDANCE (
    ATTENDANCE_ID   NUMBER          NOT NULL,
    EMP_ID          NUMBER          NOT NULL,
    WORK_DATE       DATE            NOT NULL,
    CHECK_IN        TIMESTAMP       NULL,
    CHECK_OUT       TIMESTAMP       NULL,
    WORK_HOURS      NUMBER(5,2)     NULL,
    STATUS          VARCHAR2(20)    DEFAULT 'NORMAL' NOT NULL,
    MEMO            VARCHAR2(300)   NULL,
    CREATED_AT      DATE            NULL,
    CONSTRAINT PK_ATTENDANCE PRIMARY KEY (ATTENDANCE_ID)
);

-- 의약품 마스터
CREATE TABLE PRODUCT (
    PRODUCT_ID              NUMBER          NOT NULL,
    PRODUCT_CODE            VARCHAR2(50)    NOT NULL,
    PRODUCT_NAME            VARCHAR2(300)   NOT NULL,
    MAKER_NAME              VARCHAR2(100)   NULL,
    UNIT                    VARCHAR2(50)    DEFAULT 'EA' NOT NULL,
    STANDARD_PURCHASE_PRICE NUMBER(12,2)    DEFAULT 0 NOT NULL,
    STANDARD_SALES_PRICE    NUMBER(12,2)    DEFAULT 0 NOT NULL,
    SAFETY_QTY              NUMBER          DEFAULT 0,
    IS_PRESCRIPTION         CHAR(1)         DEFAULT 'N' NOT NULL,
    STORAGE_TYPE            VARCHAR2(50)    DEFAULT 'ROOM' NOT NULL,
    STATUS                  VARCHAR2(20)    DEFAULT 'ACTIVE' NOT NULL,
    CREATED_AT              DATE            NULL,
    UPDATED_AT              DATE            NULL,
    CONSTRAINT PK_PRODUCT PRIMARY KEY (PRODUCT_ID)
);

-- 의약품 분류
CREATE TABLE PRODUCT_SPEC (
    SPEC_ID         NUMBER          NOT NULL,
    SPEC_NAME       VARCHAR2(100)   NOT NULL,
    PRODUCT_ID      NUMBER          NULL,
    DESCRIPTION     VARCHAR2(300)   NULL,
    USE_YN          CHAR(1)         DEFAULT 'Y' NOT NULL,
    CREATED_AT      DATE            NULL,
    CONSTRAINT PK_PRODUCT_SPEC PRIMARY KEY (SPEC_ID)
);

-- 공급처
CREATE TABLE SUPPLIER (
    SUPPLIER_ID     NUMBER          NOT NULL,
    SUPPLIER_NAME   VARCHAR2(100)   NOT NULL,
    BUSINESS_NO     VARCHAR2(20)    NULL,
    MANAGER_NAME    VARCHAR2(50)    NULL,
    PHONE           VARCHAR2(20)    NULL,
    ADDRESS         VARCHAR2(300)   NULL,
    STATUS          VARCHAR2(20)    DEFAULT 'ACTIVE' NOT NULL,
    CREATED_AT      DATE            NULL,
    UPDATED_AT      DATE            NULL,
    CONSTRAINT PK_SUPPLIER PRIMARY KEY (SUPPLIER_ID)
);

-- 발주 헤더
CREATE TABLE PURCHASE_ORDER (
    PO_ID           NUMBER          NOT NULL,
    SUPPLIER_ID     NUMBER          NOT NULL,
    REQUEST_EMP_ID  NUMBER          NOT NULL,
    APPROVE_EMP_ID  NUMBER          NULL,
    PO_DATE         DATE            NOT NULL,
    APPROVE_DATE    DATE            NULL,
    STATUS          VARCHAR2(20)    DEFAULT 'REQUESTED' NOT NULL,
    TOTAL_AMOUNT    NUMBER(15,2)    DEFAULT 0 NOT NULL,
    MEMO            VARCHAR2(500)   NULL,
    CREATED_AT      DATE            NULL,
    UPDATED_AT      DATE            NULL,
    CONSTRAINT PK_PURCHASE_ORDER PRIMARY KEY (PO_ID)
);

-- 발주 상세
CREATE TABLE PURCHASE_ORDER_DETAIL (
    PO_DETAIL_ID    NUMBER          NOT NULL,
    PO_ID           NUMBER          NOT NULL,
    PRODUCT_ID      NUMBER          NOT NULL,
    ORDER_QTY       NUMBER          NOT NULL,
    UNIT_PRICE      NUMBER(12,2)    NOT NULL,
    AMOUNT          NUMBER(15,2)    NOT NULL,
    CONSTRAINT PK_PO_DETAIL PRIMARY KEY (PO_DETAIL_ID)
);

-- 입고 헤더
CREATE TABLE RECEIVING (
    RECEIVING_ID        NUMBER          NOT NULL,
    PO_ID               NUMBER          NOT NULL,
    RECEIVED_EMP_ID     NUMBER          NOT NULL,
    RECEIVING_DATE      DATE            NOT NULL,
    STATUS              VARCHAR2(20)    DEFAULT 'COMPLETED' NOT NULL,
    MEMO                VARCHAR2(500)   NULL,
    CREATED_AT          DATE            NULL,
    CONSTRAINT PK_RECEIVING PRIMARY KEY (RECEIVING_ID)
);

-- 입고 상세
CREATE TABLE RECEIVING_DETAIL (
    RECEIVING_DETAIL_ID NUMBER          NOT NULL,
    RECEIVING_ID        NUMBER          NOT NULL,
    PRODUCT_ID          NUMBER          NOT NULL,
    LOT_NO              VARCHAR2(50)    NOT NULL,
    EXPIRY_DATE         DATE            NOT NULL,
    RECEIVED_QTY        NUMBER          NOT NULL,
    UNIT_PRICE          NUMBER(12,2)    NOT NULL,
    CONSTRAINT PK_RECEIVING_DETAIL PRIMARY KEY (RECEIVING_DETAIL_ID)
);

-- 재고 (로트별)
CREATE TABLE INVENTORY_LOT (
    INVENTORY_LOT_ID    NUMBER          NOT NULL,
    PRODUCT_ID          NUMBER          NOT NULL,
    LOT_NO              VARCHAR2(50)    NOT NULL,
    EXPIRY_DATE         DATE            NOT NULL,
    CURRENT_QTY         NUMBER          DEFAULT 0 NOT NULL,
    LOCATION            VARCHAR2(100)   NOT NULL,
    STATUS              VARCHAR2(20)    DEFAULT 'NORMAL' NOT NULL,
    CREATED_AT          DATE            NULL,
    LAST_MODIFIED_AT    DATE            NULL,
    CONSTRAINT PK_INVENTORY_LOT PRIMARY KEY (INVENTORY_LOT_ID)
);

-- 입출고 이력
CREATE TABLE STOCK_MOVEMENT (
    MOVEMENT_ID      NUMBER(10)   NOT NULL,
    INVENTORY_LOT_ID NUMBER(10)   NOT NULL,
    MOVEMENT_TYPE    VARCHAR2(20) NOT NULL,
    QTY              NUMBER(10)   NOT NULL,
    BEFORE_QTY       NUMBER(10)   NOT NULL,
    AFTER_QTY        NUMBER(10)   NOT NULL,
    SOURCE_TYPE      VARCHAR2(50),
    SOURCE_ID        NUMBER(10),
    CREATED_BY       NUMBER(10)   NOT NULL,
    CREATED_AT       TIMESTAMP(6),
    REASON           VARCHAR2(100),
    CONSTRAINT PK_STOCK_MOV PRIMARY KEY (MOVEMENT_ID),
    CONSTRAINT CK_STOCK_MOV_MOV_TYPE CHECK (MOVEMENT_TYPE IN ('IN','OUT','RETURN','DISPOSAL','ADJUST')),
    CONSTRAINT CK_STOCK_MOV_QTY CHECK (QTY > 0),
    CONSTRAINT CK_STOCK_MOV_BEFORE_QTY CHECK (BEFORE_QTY >= 0),
    CONSTRAINT CK_STOCK_MOV_AFTER_QTY CHECK (AFTER_QTY >= 0)
);

-- 재고 알림
CREATE TABLE INVENTORY_ALERT (
    ALERT_ID            NUMBER          NOT NULL,
    INVENTORY_LOT_ID    NUMBER          NOT NULL,
    ALERT_TYPE          VARCHAR2(20)    NOT NULL,
    MESSAGE             VARCHAR2(500)   NOT NULL,
    IS_READ             CHAR(1)         DEFAULT 'N' NOT NULL,
    CREATED_AT          DATE            NULL,
    CONSTRAINT PK_INVENTORY_ALERT PRIMARY KEY (ALERT_ID)
);

-- 거래처 (약국·병원)
CREATE TABLE CUSTOMER (
    CUSTOMER_ID         NUMBER          NOT NULL,
    CUSTOMER_NAME       VARCHAR2(100)   NOT NULL,
    CUSTOMER_TYPE       VARCHAR2(30)    NOT NULL,
    BUSINESS_NO         VARCHAR2(20)    NULL,
    CREDIT_LIMIT        NUMBER(15,2)    DEFAULT 0 NOT NULL,
    RECEIVABLE_BALANCE  NUMBER(15,2)    DEFAULT 0 NOT NULL,
    PHONE               VARCHAR2(20)    NULL,
    ADDRESS             VARCHAR2(300)   NULL,
    STATUS              VARCHAR2(20)    DEFAULT 'ACTIVE' NOT NULL,
    CREATED_AT          DATE            NULL,
    UPDATED_AT          DATE            NULL,
    CONSTRAINT PK_CUSTOMER PRIMARY KEY (CUSTOMER_ID)
);

-- 판매 주문 헤더
CREATE TABLE SALES_ORDER (
    SO_ID               NUMBER          NOT NULL,
    CUSTOMER_ID         NUMBER          NOT NULL,
    REQUEST_EMP_ID      NUMBER          NOT NULL,
    APPROVE_EMP_ID      NUMBER          NULL,
    ORDER_DATE          DATE            NOT NULL,
    APPROVE_DATE        DATE            NULL,
    STATUS              VARCHAR2(20)    DEFAULT 'REQUESTED' NOT NULL,
    TOTAL_AMOUNT        NUMBER(15,2)    DEFAULT 0 NOT NULL,
    MEMO                VARCHAR2(500)   NULL,
    CREATED_AT          DATE            NULL,
    UPDATED_AT          DATE            NULL,
    CONSTRAINT PK_SALES_ORDER PRIMARY KEY (SO_ID)
);

-- 판매 주문 상세
CREATE TABLE SALES_ORDER_DETAIL (
    SO_DETAIL_ID    NUMBER          NOT NULL,
    SO_ID           NUMBER          NOT NULL,
    PRODUCT_ID      NUMBER          NOT NULL,
    ORDER_QTY       NUMBER          NOT NULL,
    UNIT_PRICE      NUMBER(12,2)    NOT NULL,
    AMOUNT          NUMBER(15,2)    NOT NULL,
    CONSTRAINT PK_SO_DETAIL PRIMARY KEY (SO_DETAIL_ID)
);

-- 출고 헤더
CREATE TABLE SHIPMENT (
    SHIPMENT_ID     NUMBER          NOT NULL,
    SO_ID           NUMBER          NOT NULL,
    SHIPPED_EMP_ID  NUMBER          NOT NULL,
    SHIPMENT_DATE   DATE            NOT NULL,
    STATUS          VARCHAR2(20)    DEFAULT 'READY' NOT NULL,
    MEMO            VARCHAR2(500)   NULL,
    CREATED_AT      DATE            NULL,
    CONSTRAINT PK_SHIPMENT PRIMARY KEY (SHIPMENT_ID)
);

-- 출고 상세
CREATE TABLE SHIPMENT_DETAIL (
    SHIPMENT_DETAIL_ID  NUMBER  NOT NULL,
    SHIPMENT_ID         NUMBER  NOT NULL,
    SO_DETAIL_ID        NUMBER  NOT NULL,
    INVENTORY_LOT_ID    NUMBER  NOT NULL,
    PRODUCT_ID          NUMBER  NOT NULL,
    SHIPPED_QTY         NUMBER  NOT NULL,
    CONSTRAINT PK_SHIPMENT_DETAIL PRIMARY KEY (SHIPMENT_DETAIL_ID)
);

-- 반품
CREATE TABLE RETURN_REQUEST (
    RETURN_ID           NUMBER          NOT NULL,
    CUSTOMER_ID         NUMBER          NOT NULL,
    SO_ID               NUMBER          NULL,
    PRODUCT_ID          NUMBER          NOT NULL,
    INVENTORY_LOT_ID    NUMBER          NOT NULL,
    RETURN_QTY          NUMBER          NOT NULL,
    REASON              VARCHAR2(500)   NULL,
    STATUS              VARCHAR2(20)    DEFAULT 'REQUESTED' NOT NULL,
    CREATED_BY          NUMBER          NOT NULL,
    CREATED_AT          TIMESTAMP(6)    DEFAULT SYSTIMESTAMP NOT NULL,
    SHIPMENT_DETAIL_ID  NUMBER(10)      NULL,
    APPROVED_BY         NUMBER(10)      NULL,
    APPROVED_AT         TIMESTAMP(6)    NULL,
    COMPLETED_AT        TIMESTAMP(6)    NULL,
    REJECT_REASON       VARCHAR2(500)   NULL,
    RETURN_GROUP_ID     NUMBER(10)      DEFAULT 0 NOT NULL,
    CONSTRAINT PK_RETURN_ITEM PRIMARY KEY (RETURN_ID)
);

-- 폐기
CREATE TABLE DISPOSAL (
    DISPOSAL_ID         NUMBER          NOT NULL,
    INVENTORY_LOT_ID    NUMBER          NOT NULL,
    PRODUCT_ID          NUMBER          NOT NULL,
    DISPOSAL_QTY        NUMBER          NOT NULL,
    REASON              VARCHAR2(500)   NULL,
    STATUS              VARCHAR2(20)    DEFAULT 'REQUESTED' NOT NULL,
    CREATED_BY          NUMBER          NOT NULL,
    CREATED_AT          DATE            NULL,
    CONSTRAINT PK_DISPOSAL PRIMARY KEY (DISPOSAL_ID)
);

-- 매입 전표
CREATE TABLE PURCHASE_INVOICE (
    PURCHASE_INVOICE_ID NUMBER          NOT NULL,
    PO_ID               NUMBER          NOT NULL,
    SUPPLIER_ID         NUMBER          NOT NULL,
    ISSUE_DATE          DATE            NOT NULL,
    TOTAL_AMOUNT        NUMBER(15,2)    NOT NULL,
    STATUS              VARCHAR2(20)    DEFAULT 'ISSUED' NOT NULL,
    CREATED_AT          DATE            NULL,
    CONSTRAINT PK_PURCHASE_INVOICE PRIMARY KEY (PURCHASE_INVOICE_ID)
);

-- 미지급금
CREATE TABLE ACCOUNTS_PAYABLE (
    AP_ID               NUMBER          NOT NULL,
    SUPPLIER_ID         NUMBER          NOT NULL,
    PURCHASE_INVOICE_ID NUMBER          NOT NULL,
    TOTAL_AMOUNT        NUMBER(15,2)    NOT NULL,
    PAID_AMOUNT         NUMBER(15,2)    DEFAULT 0 NOT NULL,
    REMAIN_AMOUNT       NUMBER(15,2)    NOT NULL,
    DUE_DATE            DATE            NULL,
    STATUS              VARCHAR2(20)    DEFAULT 'UNPAID' NOT NULL,
    CREATED_AT          DATE            NULL,
    CONSTRAINT PK_AP PRIMARY KEY (AP_ID)
);

-- 매출 전표
CREATE TABLE SALES_INVOICE (
    SALES_INVOICE_ID    NUMBER          NOT NULL,
    SO_ID               NUMBER          NOT NULL,
    CUSTOMER_ID         NUMBER          NOT NULL,
    ISSUE_DATE          DATE            NOT NULL,
    TOTAL_AMOUNT        NUMBER(15,2)    NOT NULL,
    STATUS              VARCHAR2(20)    DEFAULT 'ISSUED' NOT NULL,
    CREATED_AT          DATE            NULL,
    CONSTRAINT PK_SALES_INVOICE PRIMARY KEY (SALES_INVOICE_ID)
);

-- 미수금
CREATE TABLE ACCOUNTS_RECEIVABLE (
    AR_ID               NUMBER          NOT NULL,
    CUSTOMER_ID         NUMBER          NOT NULL,
    SALES_INVOICE_ID    NUMBER          NOT NULL,
    TOTAL_AMOUNT        NUMBER(15,2)    NOT NULL,
    PAID_AMOUNT         NUMBER(15,2)    DEFAULT 0 NOT NULL,
    REMAIN_AMOUNT       NUMBER(15,2)    NOT NULL,
    DUE_DATE            DATE            NULL,
    STATUS              VARCHAR2(20)    DEFAULT 'UNPAID' NOT NULL,
    CREATED_AT          DATE            NULL,
    CONSTRAINT PK_AR PRIMARY KEY (AR_ID)
);

-- 수금
CREATE TABLE PAYMENT (
    PAYMENT_ID      NUMBER          NOT NULL,
    AR_ID           NUMBER          NOT NULL,
    CUSTOMER_ID     NUMBER          NOT NULL,
    PAYMENT_DATE    DATE            NOT NULL,
    PAYMENT_AMOUNT  NUMBER(15,2)    NOT NULL,
    PAYMENT_TYPE    VARCHAR2(20)    NOT NULL,
    CREATED_BY      NUMBER          NOT NULL,
    CREATED_AT      DATE            NULL,
    CONSTRAINT PK_PAYMENT PRIMARY KEY (PAYMENT_ID)
);

-- 손익 정산
CREATE TABLE SETTLEMENT (
    SETTLEMENT_ID    NUMBER          NOT NULL,
    START_DATE       DATE            NOT NULL,
    END_DATE         DATE            NOT NULL,
    TOTAL_PURCHASE   NUMBER(15,2)    DEFAULT 0 NOT NULL,
    TOTAL_SALES      NUMBER(15,2)    DEFAULT 0 NOT NULL,
    TOTAL_RECEIVABLE NUMBER(15,2)    DEFAULT 0 NOT NULL,
    TOTAL_PAYABLE    NUMBER(15,2)    DEFAULT 0 NOT NULL,
    GROSS_PROFIT     NUMBER(15,2)    DEFAULT 0 NOT NULL,
    PROFIT_RATE      NUMBER(5,2)     DEFAULT 0 NOT NULL,
    CREATED_BY       NUMBER          NOT NULL,
    CREATED_AT       DATE            NULL,
    CONSTRAINT PK_SETTLEMENT PRIMARY KEY (SETTLEMENT_ID)
);

-- 공공 API 이력
CREATE TABLE API_LOG (
    API_LOG_ID      NUMBER          NOT NULL,
    API_NAME        VARCHAR2(100)   NOT NULL,
    REQUEST_URL     VARCHAR2(1000)  NULL,
    REQUEST_PARAM   CLOB            NULL,
    RESPONSE_CODE   VARCHAR2(20)    NULL,
    RESPONSE_BODY   CLOB            NULL,
    CREATED_AT      DATE            NULL,
    CONSTRAINT PK_API_LOG PRIMARY KEY (API_LOG_ID)
);

-- AI 리포트
CREATE TABLE AI_REPORT (
    REPORT_ID       NUMBER          NOT NULL,
    REPORT_TYPE     VARCHAR2(30)    NOT NULL,
    TITLE           VARCHAR2(200)   NOT NULL,
    CONTENT         CLOB            NULL,
    CREATED_BY      NUMBER          NOT NULL,
    CREATED_AT      DATE            NOT NULL,
    CONSTRAINT PK_AI_REPORT PRIMARY KEY (REPORT_ID)
);

-- AI 쿼리 로그
CREATE TABLE AI_QUERY_LOG (
    QUERY_ID        NUMBER          NOT NULL,
    EMP_ID          NUMBER          NOT NULL,
    USER_QUESTION   CLOB            NOT NULL,
    GENERATED_SQL   CLOB            NULL,
    RESULT_SUMMARY  CLOB            NULL,
    CREATED_AT      DATE            NULL,
    CONSTRAINT PK_AI_QUERY_LOG PRIMARY KEY (QUERY_ID)
);

-- 알림
CREATE TABLE ALERT (
    ALERT_ID         NUMBER         NOT NULL,
    PRODUCT_ID       NUMBER,
    INVENTORY_LOT_ID NUMBER,
    ALERT_TYPE       VARCHAR2(30)   NOT NULL,
    MESSAGE          VARCHAR2(500)  NOT NULL,
    CREATED_AT       TIMESTAMP(6)   DEFAULT SYSTIMESTAMP,
    ALERT_LEVEL      VARCHAR2(30),
    CONSTRAINT PK_ALERT PRIMARY KEY (ALERT_ID)
);

-- 알림 상세
CREATE TABLE ALERT_DETAIL (
    ALERT_ID     NUMBER           NOT NULL,
    DEPT_ID      NUMBER           NOT NULL,
    EMP_ID       NUMBER           NOT NULL,
    ROLE_CODE    VARCHAR2(20),
    IS_READ      CHAR DEFAULT 'N' NOT NULL,
    IS_DELIVERED CHAR DEFAULT 'N' NOT NULL,
    CONSTRAINT PK_ALERT_DETAIL PRIMARY KEY (ALERT_ID, EMP_ID),
    CONSTRAINT CK_ALERT_DETAIL_IS_READ CHECK (IS_READ IN ('Y','N')),
    CONSTRAINT CK_ALERT_DETAIL_IS_DELIVERED CHECK (IS_DELIVERED IN ('Y','N'))
);

-- ============================================================
-- 3. FK 제약 일괄 추가 (모든 테이블 생성 후라 순서 무관)
-- ============================================================
ALTER TABLE EMPLOYEE ADD CONSTRAINT FK_EMP_DEPT FOREIGN KEY (DEPT_ID) REFERENCES DEPARTMENT (DEPT_ID);
ALTER TABLE ATTENDANCE ADD CONSTRAINT FK_ATT_EMP FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEE (EMP_ID);
ALTER TABLE PRODUCT_SPEC ADD CONSTRAINT FK_SPEC_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (PRODUCT_ID);
ALTER TABLE PURCHASE_ORDER ADD CONSTRAINT FK_PO_SUPPLIER FOREIGN KEY (SUPPLIER_ID) REFERENCES SUPPLIER (SUPPLIER_ID);
ALTER TABLE PURCHASE_ORDER ADD CONSTRAINT FK_PO_REQUEST_EMP FOREIGN KEY (REQUEST_EMP_ID) REFERENCES EMPLOYEE (EMP_ID);
ALTER TABLE PURCHASE_ORDER ADD CONSTRAINT FK_PO_APPROVE_EMP FOREIGN KEY (APPROVE_EMP_ID) REFERENCES EMPLOYEE (EMP_ID);
ALTER TABLE PURCHASE_ORDER_DETAIL ADD CONSTRAINT FK_PO_DETAIL_PO FOREIGN KEY (PO_ID) REFERENCES PURCHASE_ORDER (PO_ID);
ALTER TABLE PURCHASE_ORDER_DETAIL ADD CONSTRAINT FK_PO_DETAIL_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (PRODUCT_ID);
ALTER TABLE RECEIVING ADD CONSTRAINT FK_RECEIVING_PO FOREIGN KEY (PO_ID) REFERENCES PURCHASE_ORDER (PO_ID);
ALTER TABLE RECEIVING ADD CONSTRAINT FK_RECEIVING_EMP FOREIGN KEY (RECEIVED_EMP_ID) REFERENCES EMPLOYEE (EMP_ID);
ALTER TABLE RECEIVING_DETAIL ADD CONSTRAINT FK_RCV_DTL_RECEIVING FOREIGN KEY (RECEIVING_ID) REFERENCES RECEIVING (RECEIVING_ID);
ALTER TABLE RECEIVING_DETAIL ADD CONSTRAINT FK_RCV_DTL_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (PRODUCT_ID);
ALTER TABLE INVENTORY_LOT ADD CONSTRAINT FK_INV_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (PRODUCT_ID);
ALTER TABLE STOCK_MOVEMENT ADD CONSTRAINT FK_STOCK_MOV_INV_LOT_ID FOREIGN KEY (INVENTORY_LOT_ID) REFERENCES INVENTORY_LOT (INVENTORY_LOT_ID);
ALTER TABLE STOCK_MOVEMENT ADD CONSTRAINT FK_STOCK_MOV_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES EMPLOYEE (EMP_ID);
ALTER TABLE INVENTORY_ALERT ADD CONSTRAINT FK_ALERT_LOT FOREIGN KEY (INVENTORY_LOT_ID) REFERENCES INVENTORY_LOT (INVENTORY_LOT_ID);
ALTER TABLE SALES_ORDER ADD CONSTRAINT FK_SO_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER (CUSTOMER_ID);
ALTER TABLE SALES_ORDER ADD CONSTRAINT FK_SO_REQUEST_EMP FOREIGN KEY (REQUEST_EMP_ID) REFERENCES EMPLOYEE (EMP_ID);
ALTER TABLE SALES_ORDER ADD CONSTRAINT FK_SO_APPROVE_EMP FOREIGN KEY (APPROVE_EMP_ID) REFERENCES EMPLOYEE (EMP_ID);
ALTER TABLE SALES_ORDER_DETAIL ADD CONSTRAINT FK_SO_DETAIL_SO FOREIGN KEY (SO_ID) REFERENCES SALES_ORDER (SO_ID);
ALTER TABLE SALES_ORDER_DETAIL ADD CONSTRAINT FK_SO_DETAIL_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (PRODUCT_ID);
ALTER TABLE SHIPMENT ADD CONSTRAINT FK_SHIPMENT_SO FOREIGN KEY (SO_ID) REFERENCES SALES_ORDER (SO_ID);
ALTER TABLE SHIPMENT ADD CONSTRAINT FK_SHIPMENT_EMP FOREIGN KEY (SHIPPED_EMP_ID) REFERENCES EMPLOYEE (EMP_ID);
ALTER TABLE SHIPMENT_DETAIL ADD CONSTRAINT FK_SHIP_DTL_SHIPMENT FOREIGN KEY (SHIPMENT_ID) REFERENCES SHIPMENT (SHIPMENT_ID);
ALTER TABLE SHIPMENT_DETAIL ADD CONSTRAINT FK_SHIP_DTL_SO_DETAIL FOREIGN KEY (SO_DETAIL_ID) REFERENCES SALES_ORDER_DETAIL (SO_DETAIL_ID);
ALTER TABLE SHIPMENT_DETAIL ADD CONSTRAINT FK_SHIP_DTL_LOT FOREIGN KEY (INVENTORY_LOT_ID) REFERENCES INVENTORY_LOT (INVENTORY_LOT_ID);
ALTER TABLE RETURN_REQUEST ADD CONSTRAINT FK_RETURN_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER (CUSTOMER_ID);
ALTER TABLE RETURN_REQUEST ADD CONSTRAINT FK_RETURN_LOT FOREIGN KEY (INVENTORY_LOT_ID) REFERENCES INVENTORY_LOT (INVENTORY_LOT_ID);
ALTER TABLE RETURN_REQUEST ADD CONSTRAINT FK_RET_REQ_SHIP_DETAIL FOREIGN KEY (SHIPMENT_DETAIL_ID) REFERENCES SHIPMENT_DETAIL (SHIPMENT_DETAIL_ID);
ALTER TABLE RETURN_REQUEST ADD CONSTRAINT FK_RET_REQ_APPROVED_BY FOREIGN KEY (APPROVED_BY) REFERENCES EMPLOYEE (EMP_ID);
ALTER TABLE DISPOSAL ADD CONSTRAINT FK_DISPOSAL_LOT FOREIGN KEY (INVENTORY_LOT_ID) REFERENCES INVENTORY_LOT (INVENTORY_LOT_ID);
ALTER TABLE DISPOSAL ADD CONSTRAINT FK_DISPOSAL_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (PRODUCT_ID);
ALTER TABLE PURCHASE_INVOICE ADD CONSTRAINT FK_PI_PO FOREIGN KEY (PO_ID) REFERENCES PURCHASE_ORDER (PO_ID);
ALTER TABLE PURCHASE_INVOICE ADD CONSTRAINT FK_PI_SUPPLIER FOREIGN KEY (SUPPLIER_ID) REFERENCES SUPPLIER (SUPPLIER_ID);
ALTER TABLE ACCOUNTS_PAYABLE ADD CONSTRAINT FK_AP_SUPPLIER FOREIGN KEY (SUPPLIER_ID) REFERENCES SUPPLIER (SUPPLIER_ID);
ALTER TABLE ACCOUNTS_PAYABLE ADD CONSTRAINT FK_AP_INVOICE FOREIGN KEY (PURCHASE_INVOICE_ID) REFERENCES PURCHASE_INVOICE (PURCHASE_INVOICE_ID);
ALTER TABLE SALES_INVOICE ADD CONSTRAINT FK_SI_SO FOREIGN KEY (SO_ID) REFERENCES SALES_ORDER (SO_ID);
ALTER TABLE SALES_INVOICE ADD CONSTRAINT FK_SI_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER (CUSTOMER_ID);
ALTER TABLE ACCOUNTS_RECEIVABLE ADD CONSTRAINT FK_AR_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER (CUSTOMER_ID);
ALTER TABLE ACCOUNTS_RECEIVABLE ADD CONSTRAINT FK_AR_INVOICE FOREIGN KEY (SALES_INVOICE_ID) REFERENCES SALES_INVOICE (SALES_INVOICE_ID);
ALTER TABLE PAYMENT ADD CONSTRAINT FK_PAYMENT_AR FOREIGN KEY (AR_ID) REFERENCES ACCOUNTS_RECEIVABLE (AR_ID);
ALTER TABLE PAYMENT ADD CONSTRAINT FK_PAYMENT_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER (CUSTOMER_ID);
ALTER TABLE SETTLEMENT ADD CONSTRAINT FK_SETTLEMENT_EMP FOREIGN KEY (CREATED_BY) REFERENCES EMPLOYEE (EMP_ID);
ALTER TABLE AI_REPORT ADD CONSTRAINT FK_AI_REPORT_EMP FOREIGN KEY (CREATED_BY) REFERENCES EMPLOYEE (EMP_ID);
ALTER TABLE AI_QUERY_LOG ADD CONSTRAINT FK_AI_QUERY_EMP FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEE (EMP_ID);
ALTER TABLE ALERT_DETAIL ADD CONSTRAINT FK_ALERT_DETAIL_ALERT FOREIGN KEY (ALERT_ID) REFERENCES ALERT (ALERT_ID);
ALTER TABLE ALERT_DETAIL ADD CONSTRAINT FK_ALERT_DETAIL_EMP FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEE (EMP_ID);

-- ============================================================
-- 4. 인덱스
-- ============================================================
CREATE INDEX IX_STOCK_MOV_INV_LOT_ID ON STOCK_MOVEMENT (INVENTORY_LOT_ID);
CREATE INDEX IX_STOCK_MOV_CREATED_BY ON STOCK_MOVEMENT (CREATED_BY);

COMMIT;
